### ISSUE TITLE
sentry: take Hub from context or fallback to the global one

### ISSUE THREAD

**Issue by Pitasi** [damianopetrungaro/golog#54]
Hi @damianopetrungaro, thank you for golog :) 

I'm trying to log errors to Sentry, and saw that you already provide a [Sentry Writer](https://github.com/damianopetrungaro/golog/blob/main/sentry/sentry.go). The only problem I see with it is that it must be initialized with a sentry.Hub, while in reality I think it should use the Hub contained in the context if any (see for example [the Sentry http middleware](https://github.com/getsentry/sentry-go/blob/master/http/sentryhttp.go#L84-L88) usage, it's also worth pointing out that the Hub struct is not concurrent safe for writing, that's why it's cloned when not found in the context).

I can open a PR if you want me to 😃

**Comment by Pitasi** [comment]
It's part of the Sentry package, not my decision. They use this non concurrent-safe Hub object that must be cloned and instantiated for each request.

If golog wants to support Sentry properly (eg. in HTTP servers), we should use the Hub already contained in the context (my PR implements that).

**Comment by damianopetrungaro** [comment]
@Pitasi getting it from the `ctx` doesn't really make it concurrent safe, I've seen the source code (as well as the documentation), we should call the `Clone` method to return a new hub, this is the [recommended way](https://docs.sentry.io/platforms/go/concurrency/) as far as I can see.

Do you agree with it? Any feedback?

off topic:

(in general, I'd argue that maintaining a concurrent safe logger in the codebase is really a bad approach, but we can't fix it since it is in the sentry package).

**Comment by damianopetrungaro** [comment]
Hey @Pitasi any update? 

I do think this is an important feature/fix to release so any progress on this would be amazing!

**Comment by Pitasi** [comment]
> we should call the Clone method to return a new hub, this is the [recommended way](https://docs.sentry.io/platforms/go/concurrency/) as far as I can see

Yes cloning the hub truly solves the concurrency issue, but...😁 The hub contained in the context is pre-populated with other informations (HTTP headers, client ip, and all other http request specific stuff), if we don't use that hub we'd lose that.

And getting it from the context to clone it everytime we log something sounds like an overkill (but maybe it is not tbh, I'm conflicted about it).
